title: AthletiCheck
description: A application that targets Athletic Trainers and Athletes for better communication and treatment experience.
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
